/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author lemon
 */
public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrameAddItem = new javax.swing.JInternalFrame();
        textFieldAddItemHeader = new javax.swing.JTextField();
        layeredPaneAddItemContent = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scrollPaneDescription = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();
        buttonAddItem = new javax.swing.JButton();
        buttonCancelAddItem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(640, 480));

        internalFrameAddItem.setBorder(null);
        internalFrameAddItem.setClosable(true);
        internalFrameAddItem.setTitle("Add Product");
        internalFrameAddItem.setFrameIcon(null);
        internalFrameAddItem.setMaximumSize(new java.awt.Dimension(480, 300));
        internalFrameAddItem.setOpaque(true);
        internalFrameAddItem.setPreferredSize(new java.awt.Dimension(480, 300));
        internalFrameAddItem.setVisible(true);
        internalFrameAddItem.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                internalFrameAddItemInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        textFieldAddItemHeader.setEditable(false);
        textFieldAddItemHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textFieldAddItemHeader.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldAddItemHeader.setText("Add Product");
        textFieldAddItemHeader.setBorder(null);
        textFieldAddItemHeader.setFocusable(false);
        textFieldAddItemHeader.setName("popupTitle"); // NOI18N
        textFieldAddItemHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAddItemHeaderActionPerformed(evt);
            }
        });

        layeredPaneAddItemContent.setBackground(new java.awt.Color(76, 76, 76));
        layeredPaneAddItemContent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 50, 50), 1, true));
        layeredPaneAddItemContent.setFocusable(false);
        layeredPaneAddItemContent.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Product Name:");

        jFormattedTextField1.setBorder(null);
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.setText("Product Name");
        jFormattedTextField1.setToolTipText("Enter the new product's name");
        jFormattedTextField1.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFormattedTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Purchase Price:");

        jFormattedTextField2.setBorder(null);
        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField2.setText("Purchase Price");
        jFormattedTextField2.setToolTipText("Enter the new product's purchase price");
        jFormattedTextField2.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFormattedTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        jFormattedTextField3.setBorder(null);
        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField3.setText("Purchase Date");
        jFormattedTextField3.setToolTipText("Enter the new product's purchase date");
        jFormattedTextField3.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFormattedTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Purchase Date:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Description:");

        scrollPaneDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        textAreaDescription.setColumns(20);
        textAreaDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAreaDescription.setLineWrap(true);
        textAreaDescription.setRows(3);
        textAreaDescription.setText("Product description");
        textAreaDescription.setToolTipText("Enter the new product's description");
        textAreaDescription.setWrapStyleWord(true);
        scrollPaneDescription.setViewportView(textAreaDescription);

        layeredPaneAddItemContent.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneAddItemContent.setLayer(jFormattedTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneAddItemContent.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneAddItemContent.setLayer(jFormattedTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneAddItemContent.setLayer(jFormattedTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneAddItemContent.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneAddItemContent.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneAddItemContent.setLayer(scrollPaneDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layeredPaneAddItemContentLayout = new javax.swing.GroupLayout(layeredPaneAddItemContent);
        layeredPaneAddItemContent.setLayout(layeredPaneAddItemContentLayout);
        layeredPaneAddItemContentLayout.setHorizontalGroup(
            layeredPaneAddItemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneAddItemContentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layeredPaneAddItemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layeredPaneAddItemContentLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(96, 96, 96)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layeredPaneAddItemContentLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(110, 110, 110)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layeredPaneAddItemContentLayout.createSequentialGroup()
                        .addGroup(layeredPaneAddItemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layeredPaneAddItemContentLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(82, 82, 82))
                            .addGroup(layeredPaneAddItemContentLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layeredPaneAddItemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(scrollPaneDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(35, 35, 35))
        );
        layeredPaneAddItemContentLayout.setVerticalGroup(
            layeredPaneAddItemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneAddItemContentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layeredPaneAddItemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layeredPaneAddItemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layeredPaneAddItemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layeredPaneAddItemContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layeredPaneAddItemContentLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollPaneDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addContainerGap())
        );

        buttonAddItem.setBackground(new java.awt.Color(78, 110, 82));
        buttonAddItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonAddItem.setText("Add");
        buttonAddItem.setToolTipText("Add a new product to the subcategory");
        buttonAddItem.setBorderPainted(false);
        buttonAddItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonAddItem.setFocusPainted(false);
        buttonAddItem.setFocusable(false);
        buttonAddItem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddItemActionPerformed(evt);
            }
        });

        buttonCancelAddItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonCancelAddItem.setText("Cancel");
        buttonCancelAddItem.setToolTipText("Cancel the addition of a new product");
        buttonCancelAddItem.setBorderPainted(false);
        buttonCancelAddItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCancelAddItem.setFocusPainted(false);
        buttonCancelAddItem.setFocusable(false);
        buttonCancelAddItem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCancelAddItem.setPreferredSize(new java.awt.Dimension(85, 32));
        buttonCancelAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelAddItemMouseClicked(evt);
            }
        });
        buttonCancelAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelAddItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout internalFrameAddItemLayout = new javax.swing.GroupLayout(internalFrameAddItem.getContentPane());
        internalFrameAddItem.getContentPane().setLayout(internalFrameAddItemLayout);
        internalFrameAddItemLayout.setHorizontalGroup(
            internalFrameAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textFieldAddItemHeader, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(internalFrameAddItemLayout.createSequentialGroup()
                .addGroup(internalFrameAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(internalFrameAddItemLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(buttonAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(buttonCancelAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(internalFrameAddItemLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(layeredPaneAddItemContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        internalFrameAddItemLayout.setVerticalGroup(
            internalFrameAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalFrameAddItemLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(textFieldAddItemHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(layeredPaneAddItemContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(internalFrameAddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalFrameAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalFrameAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldAddItemHeaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAddItemHeaderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAddItemHeaderActionPerformed

    private void buttonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddItemActionPerformed

    private void buttonCancelAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelAddItemMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonCancelAddItemMouseClicked

    private void buttonCancelAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelAddItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelAddItemActionPerformed

    private void internalFrameAddItemInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_internalFrameAddItemInternalFrameClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_internalFrameAddItemInternalFrameClosed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new AddProduct().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
             java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddItem;
    private javax.swing.JButton buttonCancelAddItem;
    private javax.swing.JInternalFrame internalFrameAddItem;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane layeredPaneAddItemContent;
    private javax.swing.JScrollPane scrollPaneDescription;
    private javax.swing.JTextArea textAreaDescription;
    private javax.swing.JTextField textFieldAddItemHeader;
    // End of variables declaration//GEN-END:variables
}
