/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.CardLayout;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author kwinl
 */
public class Categories extends javax.swing.JFrame {

    /**
     * Creates new form Categories
     */
    public Categories() {
        initComponents();
    }
        

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneCategories = new javax.swing.JScrollPane();
        listCategories = new javax.swing.JList<>();
        SubMenu = new javax.swing.JLayeredPane();
        SM0 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        SM1 = new javax.swing.JScrollPane();
        Sub1 = new javax.swing.JList<>();
        SM2 = new javax.swing.JScrollPane();
        Sub2 = new javax.swing.JList<>();
        SM3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        SM4 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        SM5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        AddCat = new javax.swing.JButton();
        DeleteCat = new javax.swing.JButton();
        AddSub = new javax.swing.JButton();
        DeleteSub = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        textFieldProductsPageTitle = new javax.swing.JTextField();
        labelItemsTitle = new javax.swing.JLabel();
        labelDetailsTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        scrollPaneCategories.setBorder(null);

        listCategories.setBorder(null);
        listCategories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Electronics", "Food", "Clothes", "Furniture", "Jewelry" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCategories.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCategoriesValueChanged(evt);
            }
        });
        scrollPaneCategories.setViewportView(listCategories);

        SubMenu.setBackground(new java.awt.Color(0, 0, 0));
        SubMenu.setOpaque(true);
        SubMenu.setLayout(new java.awt.CardLayout());

        SM0.setBorder(null);

        jList4.setBorder(null);
        SM0.setViewportView(jList4);

        SubMenu.add(SM0, "x");

        SM1.setBorder(null);

        Sub1.setBorder(null);
        Sub1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "TVs", "Radios", "Phones" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        SM1.setViewportView(Sub1);

        SubMenu.add(SM1, "c1");

        SM2.setBorder(null);

        Sub2.setBorder(null);
        Sub2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Breakfast", "Lunch", "Dinner", "Frozen" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        Sub2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SM2.setViewportView(Sub2);

        SubMenu.add(SM2, "c2");

        SM3.setBorder(null);

        jList1.setBorder(null);
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Shirts", "Pants", "Jackets", "Shoes" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        SM3.setViewportView(jList1);

        SubMenu.add(SM3, "c3");

        SM4.setBorder(null);

        jList2.setBorder(null);
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Chairs", "Tables", "Beds", "Desks" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        SM4.setViewportView(jList2);

        SubMenu.add(SM4, "c4");

        SM5.setBorder(null);

        jList3.setBorder(null);
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Earrings", "Necklaces", "Bracelets", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        SM5.setViewportView(jList3);

        SubMenu.add(SM5, "c5");

        AddCat.setText("Add");
        AddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCatActionPerformed(evt);
            }
        });

        DeleteCat.setText("Delete");
        DeleteCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteCatActionPerformed(evt);
            }
        });

        AddSub.setText("Add");

        DeleteSub.setText("Delete");
        DeleteSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSubActionPerformed(evt);
            }
        });

        jButton2.setText("<--");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("-->");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("<--");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("-->");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        textFieldProductsPageTitle.setEditable(false);
        textFieldProductsPageTitle.setBackground(new java.awt.Color(30, 140, 170));
        textFieldProductsPageTitle.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        textFieldProductsPageTitle.setForeground(new java.awt.Color(220, 220, 220));
        textFieldProductsPageTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldProductsPageTitle.setText("Inventory");
        textFieldProductsPageTitle.setBorder(null);
        textFieldProductsPageTitle.setFocusable(false);
        textFieldProductsPageTitle.setOpaque(true);
        textFieldProductsPageTitle.setRequestFocusEnabled(false);

        labelItemsTitle.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        labelItemsTitle.setText("Categories");

        labelDetailsTitle.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        labelDetailsTitle.setText("Subcategories");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddCat)
                                .addGap(26, 26, 26)
                                .addComponent(DeleteCat))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelItemsTitle)
                                .addComponent(scrollPaneCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SubMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(AddSub)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DeleteSub)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(26, 26, 26)
                                .addComponent(jButton5))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDetailsTitle)
                        .addGap(8, 8, 8)))
                .addGap(108, 108, 108))
            .addComponent(textFieldProductsPageTitle)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(textFieldProductsPageTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDetailsTitle)
                    .addComponent(labelItemsTitle))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SubMenu)
                    .addComponent(scrollPaneCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCat)
                    .addComponent(DeleteCat)
                    .addComponent(AddSub)
                    .addComponent(DeleteSub))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCategoriesValueChanged
        // TODO add your handling code here:
        CardLayout cl = (CardLayout) (SubMenu.getLayout());
        cl.show(SubMenu, "c" + (listCategories.getSelectedIndex() + 1));
    }//GEN-LAST:event_listCategoriesValueChanged

    private void DeleteCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteCatActionPerformed
        // TODO add your handling code here:
        new DeleteCategory().setVisible(true);
    }//GEN-LAST:event_DeleteCatActionPerformed

    private void DeleteSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteSubActionPerformed

    private void AddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCatActionPerformed
        listCategories.setSelectedIndex(4);
    }//GEN-LAST:event_AddCatActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

     


    try {
        javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new javax.swing.JFrame().setVisible(true);
            }
        });
    } catch (UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCat;
    private javax.swing.JButton AddSub;
    private javax.swing.JButton DeleteCat;
    private javax.swing.JButton DeleteSub;
    private javax.swing.JScrollPane SM0;
    private javax.swing.JScrollPane SM1;
    private javax.swing.JScrollPane SM2;
    private javax.swing.JScrollPane SM3;
    private javax.swing.JScrollPane SM4;
    private javax.swing.JScrollPane SM5;
    private javax.swing.JList<String> Sub1;
    private javax.swing.JList<String> Sub2;
    private javax.swing.JLayeredPane SubMenu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JLabel labelDetailsTitle;
    private javax.swing.JLabel labelItemsTitle;
    private javax.swing.JList<String> listCategories;
    private javax.swing.JScrollPane scrollPaneCategories;
    private javax.swing.JTextField textFieldProductsPageTitle;
    // End of variables declaration//GEN-END:variables
}
