/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author lemon
 */
public class ErrorPopup extends javax.swing.JFrame {

    String errorMessage = "Placeholder error message.";
    /**
     * Creates new form ErrorPopup
     */
    public ErrorPopup() {
        initComponents();
    }
    
    public ErrorPopup(String error) {
        errorMessage = error;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrameError = new javax.swing.JInternalFrame();
        textFieldErrorHeader = new javax.swing.JTextField();
        buttonOkay = new javax.swing.JButton();
        scrollPaneErrorMessage = new javax.swing.JScrollPane();
        editorPaneErrorMessage = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(480, 300));

        internalFrameError.setBorder(null);
        internalFrameError.setClosable(true);
        internalFrameError.setTitle("Error");
        internalFrameError.setFrameIcon(null);
        internalFrameError.setMaximumSize(new java.awt.Dimension(480, 300));
        internalFrameError.setOpaque(true);
        internalFrameError.setPreferredSize(new java.awt.Dimension(480, 300));
        internalFrameError.setVisible(true);
        internalFrameError.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                internalFrameErrorInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        textFieldErrorHeader.setEditable(false);
        textFieldErrorHeader.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        textFieldErrorHeader.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldErrorHeader.setText("Error:");
        textFieldErrorHeader.setBorder(null);
        textFieldErrorHeader.setFocusable(false);
        textFieldErrorHeader.setName("popupTitle"); // NOI18N

        buttonOkay.setBackground(new java.awt.Color(78, 80, 82));
        buttonOkay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonOkay.setText("Okay");
        buttonOkay.setBorderPainted(false);
        buttonOkay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonOkay.setFocusPainted(false);
        buttonOkay.setFocusable(false);
        buttonOkay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkayActionPerformed(evt);
            }
        });

        scrollPaneErrorMessage.setBackground(new java.awt.Color(30, 30, 30));
        scrollPaneErrorMessage.setBorder(null);

        editorPaneErrorMessage.setEditable(false);
        editorPaneErrorMessage.setBackground(new java.awt.Color(30, 30, 30));
        editorPaneErrorMessage.setBorder(null);
        editorPaneErrorMessage.setContentType("text/html"); // NOI18N
        editorPaneErrorMessage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        editorPaneErrorMessage.setForeground(new java.awt.Color(190, 120, 120));
        editorPaneErrorMessage.setText("<p align=\"center\">" + this.errorMessage + "</p>");
        editorPaneErrorMessage.setFocusable(false);
        editorPaneErrorMessage.setOpaque(false);
        editorPaneErrorMessage.setRequestFocusEnabled(false);
        scrollPaneErrorMessage.setViewportView(editorPaneErrorMessage);

        javax.swing.GroupLayout internalFrameErrorLayout = new javax.swing.GroupLayout(internalFrameError.getContentPane());
        internalFrameError.getContentPane().setLayout(internalFrameErrorLayout);
        internalFrameErrorLayout.setHorizontalGroup(
            internalFrameErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textFieldErrorHeader, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(internalFrameErrorLayout.createSequentialGroup()
                .addGroup(internalFrameErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(internalFrameErrorLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(buttonOkay, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(internalFrameErrorLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(scrollPaneErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        internalFrameErrorLayout.setVerticalGroup(
            internalFrameErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalFrameErrorLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(textFieldErrorHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonOkay, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(internalFrameError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(internalFrameError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkayActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_buttonOkayActionPerformed

    private void internalFrameErrorInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_internalFrameErrorInternalFrameClosed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_internalFrameErrorInternalFrameClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new ErrorPopup().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErrorPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOkay;
    private javax.swing.JEditorPane editorPaneErrorMessage;
    private javax.swing.JInternalFrame internalFrameError;
    private javax.swing.JScrollPane scrollPaneErrorMessage;
    private javax.swing.JTextField textFieldErrorHeader;
    // End of variables declaration//GEN-END:variables
}
