/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PopUps;



/**
 *
 * @author mrswi
 */
public class DeleteCategory extends javax.swing.JFrame {
    
    private String catType = "Subcategory";
    private String catName = "Shoes";
    /**
     * Creates new form DeleteCategory
     */
    public DeleteCategory() {
        initComponents();
    }
    public DeleteCategory(String deleteType, String deleteName) {
        catType = deleteType;
        catName = deleteName;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CatDelTitle = new javax.swing.JInternalFrame();
        jTextField1 = new javax.swing.JTextField();
        CatDelCon = new javax.swing.JButton();
        CatDelCan = new javax.swing.JButton();
        CatDelLayered = new javax.swing.JLayeredPane();
        CatDelTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Confirm Delete");
        setAlwaysOnTop(true);
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));
        setName("DelCatFrame"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        CatDelTitle.setBorder(null);
        CatDelTitle.setClosable(true);
        CatDelTitle.setTitle("Confirm Delete");
        CatDelTitle.setFrameIcon(null);
        CatDelTitle.setMaximumSize(new java.awt.Dimension(640, 480));
        CatDelTitle.setOpaque(true);
        CatDelTitle.setPreferredSize(new java.awt.Dimension(640, 480));
        CatDelTitle.setVisible(true);
        CatDelTitle.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                CatDelTitleInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Are you sure?");
        jTextField1.setBorder(null);
        jTextField1.setFocusable(false);
        jTextField1.setName("popupTitle"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        CatDelCon.setBackground(new java.awt.Color(150, 80, 82));
        CatDelCon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CatDelCon.setText("Delete");
        CatDelCon.setBorderPainted(false);
        CatDelCon.setFocusPainted(false);
        CatDelCon.setFocusable(false);
        CatDelCon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CatDelCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatDelConActionPerformed(evt);
            }
        });

        CatDelCan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CatDelCan.setText("Cancel");
        CatDelCan.setBorderPainted(false);
        CatDelCan.setFocusPainted(false);
        CatDelCan.setFocusable(false);
        CatDelCan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CatDelCan.setPreferredSize(new java.awt.Dimension(85, 32));
        CatDelCan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatDelCanMouseClicked(evt);
            }
        });
        CatDelCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatDelCanActionPerformed(evt);
            }
        });

        CatDelLayered.setBackground(new java.awt.Color(76, 76, 76));
        CatDelLayered.setFocusable(false);
        CatDelLayered.setOpaque(true);

        CatDelTxt.setBackground(new java.awt.Color(76, 76, 76));
        CatDelTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CatDelTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CatDelTxt.setText("<html><center>You are about to delete the " + catType + " \"<em>" + catName + "</em>\". Did you mean to perform this action?<br><br>Press \"<em>Delete</em>\" to delete the " + catType + ", or \"<em>Cancel</em>\" to cancel and return to the previous window.");
        CatDelTxt.setAlignmentX(0.5F);
        CatDelTxt.setFocusable(false);
        CatDelTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CatDelTxt.setIconTextGap(10);
        CatDelTxt.setInheritsPopupMenu(false);
        CatDelTxt.setOpaque(true);
        CatDelTxt.setPreferredSize(new java.awt.Dimension(520, 270));

        CatDelLayered.setLayer(CatDelTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout CatDelLayeredLayout = new javax.swing.GroupLayout(CatDelLayered);
        CatDelLayered.setLayout(CatDelLayeredLayout);
        CatDelLayeredLayout.setHorizontalGroup(
            CatDelLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CatDelLayeredLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CatDelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CatDelLayeredLayout.setVerticalGroup(
            CatDelLayeredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CatDelLayeredLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(CatDelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout CatDelTitleLayout = new javax.swing.GroupLayout(CatDelTitle.getContentPane());
        CatDelTitle.getContentPane().setLayout(CatDelTitleLayout);
        CatDelTitleLayout.setHorizontalGroup(
            CatDelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CatDelTitleLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(CatDelTitleLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(CatDelCon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(CatDelCan, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CatDelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CatDelLayered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        CatDelTitleLayout.setVerticalGroup(
            CatDelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CatDelTitleLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(CatDelLayered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(CatDelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatDelCan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CatDelCon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(CatDelTitle);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:;
    }//GEN-LAST:event_formWindowLostFocus

    private void CatDelTitleInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_CatDelTitleInternalFrameClosed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CatDelTitleInternalFrameClosed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void CatDelConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatDelConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatDelConActionPerformed

    private void CatDelCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatDelCanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatDelCanActionPerformed

    private void CatDelCanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatDelCanMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CatDelCanMouseClicked

    /**
     * @param args the command line arguments
     */


        /* Create and display the form */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CatDelCan;
    private javax.swing.JButton CatDelCon;
    private javax.swing.JLayeredPane CatDelLayered;
    private javax.swing.JInternalFrame CatDelTitle;
    private javax.swing.JLabel CatDelTxt;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
